/*
 * ecgApplet.java
 *
 * See EcgLicense.txt for License terms.
 */

/**
 *
 * @author  Mauricio Villarroel (m.villarroel@acm.og)
 */

import javax.swing.UIManager;

public class EcgMainApplet extends javax.swing.JApplet {
    
    /** Initializes the applet ecgApplet */
    public void init() {
        try{
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch(Exception e){
            throw new RuntimeException(e);
        }
        initComponents();
    }
    
    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jDesktopPane1 = new javax.swing.JDesktopPane();
        appLaunch = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        appLaunch.setText("Launch Application");
        appLaunch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appLaunchActionPerformed(evt);
            }
        });

        appLaunch.setBounds(10, 50, 230, 25);
        jDesktopPane1.add(appLaunch, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setFont(new java.awt.Font("MS Sans Serif", 1, 18));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Java ECG Generator");
        jLabel1.setBounds(10, 10, 230, 30);
        jDesktopPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(jDesktopPane1, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents

    private void appLaunchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appLaunchActionPerformed
        // TODO add your handling code here:
        launchApp();
    }//GEN-LAST:event_appLaunchActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton appLaunch;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    private void launchApp() {
        EcgApplication ecgApp = new EcgApplication();
        //ecgApp.setVisible(false);
        //ecgApp.setUndecorated(true);
        //ecgApp.setVisible(true);
        //ecgApp.setSize(800,600);
        //ecgApp.setTitle("ECG application");
        ecgApp.show();        
    }    
}
