class MODEL_CONSTANT:
    INPUT_ADAPTION_THRESHOLD = 0.001

    LEARNING_RATE_FOR_BEST_NODE = 0.1
    LEARNING_RATE_FOR_NEIGHBOR = 0.01

    OUTPUT_ADAPTION_THRESHOLD= -0.05
    OUTPUT_ADAPTION_LEARNING_RATE= 0.1

    INSERTION_TOLERANCE = 0.01
    INSERTION_LEARNING_RATE = 0.1

    DELETION_THRESHOLD = 0.01
    MINIMAL_AGE = 0.01
    SUFFICIENT_STABLILIZATION= 0.01

    TL = 100
    TS = 10
    TY = 100
    TV = 100

    MAXIMUM_EDGE_AGE = 50
